package rules.forward

import com.ftn.sbnz.model.models.Move;
import com.ftn.sbnz.model.models.Board;
import com.ftn.sbnz.model.models.Tile;
import com.ftn.sbnz.model.models.Player;
import com.ftn.sbnz.model.models.GameState;

rule "Block Enemy Color"
    when
        $m : Move($targetRow : targetRow)
        $b : Board($rows : rows)
        $player : Player(board == $b)
        $gameState : GameState($players : players)
        $enemy : Player(id != $player.getId(), $enemyBoard : board) from $players
        eval($targetRow >= 0)
        $tile : Tile($color : color) from $rows.get($targetRow)
        $enemyRows : java.util.List() from $enemyBoard.getRows()
        exists( Tile(color == $color) from $enemyRows )
    then
        $m.setScore($m.getScore() + 8);
        String message = "Blocking enemy's needed color!";
        $m.addAppliedRule(true, message);
end
