package rules.forward

import com.ftn.sbnz.model.models.Move;
import com.ftn.sbnz.model.models.Board;
import com.ftn.sbnz.model.models.Tile;

rule "Continue existing row"
    when
        $m : Move($targetRow : targetRow)
        $b : Board($rows : rows)
        eval($targetRow >= 0)
        $targetRowList : java.util.List() from $rows.get($targetRow)
        eval($targetRowList != null && $targetRowList.size() > 1)
    then
        $m.setScore($m.getScore() + 3);
        String message = "You continue a row you've already been building with this move.";
        $m.addAppliedRule(true, message);
end
