package rules.forward

import com.ftn.sbnz.model.models.Move;
import com.ftn.sbnz.model.models.Board;
import com.ftn.sbnz.model.models.Tile;

rule "Floor overflow"
    when
        $m : Move($takenTiles : takenTiles)
        $b : Board($floor : floor)
        exists( Tile( $fId : id ) from $floor and
                Tile( $tId : id ) from $takenTiles and
                eval($fId != null && $tId != null && $fId.equals($tId)) )
    then
        $m.setScore($m.getScore() - 10);
        String message = "You let one or more tiles fall to the floor with this move.";
        $m.addAppliedRule(false, message);
end