package rules.forward

import com.ftn.sbnz.model.models.Move;
import com.ftn.sbnz.model.models.Board;
import com.ftn.sbnz.model.models.Tile;
import com.ftn.sbnz.model.models.Player;

rule "Row Priority - Higher rows are better"
    when
        $m : Move($targetRow : targetRow)
        eval($targetRow >= 0 && $targetRow <= 4)
    then
        int points = $targetRow + 1;
        $m.setScore($m.getScore() + points);
end
